// This file is automatically generated. Do not edit it directly.
import {
  createClient,
  type Session,
  type AuthChangeEvent,
  type SignUpWithPasswordCredentials,
} from "@supabase/supabase-js";
import type { Database } from "./types";

console.log("🔌 [SUPABASE] Initializing Supabase client");

// Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in `.env` (see `.env.example`).
// Fallbacks keep local clones working until env is configured.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://cangdkjmtujxhinwjpva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "sb_publishable_SDUST2Q5QNKfeozH6pgA9A_d-LvMDgD";

if (!import.meta.env.VITE_SUPABASE_URL) {
  console.warn(
    "🔌 [SUPABASE] VITE_SUPABASE_URL not set - using bundled fallback. Prefer `.env`.",
  );
}

console.log(`🔌 [SUPABASE] Using URL: ${SUPABASE_URL}`);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with debug logging and Realtime configuration
const supabaseClient = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage, // localStorage is fine, but session won't persist across browser close
      persistSession: false, // Disable session persistence
      autoRefreshToken: true, // Still useful for long-lived active sessions within a single use
      debug: true,
    },
    realtime: {
      params: {
        log_level: "info", // Enable logging for Realtime connections
      },
    },
  },
);

// Add logging for auth state changes for debugging
supabaseClient.auth.onAuthStateChange((event, session) => {
  console.log(
    `🔌 [SUPABASE_RAW_CLIENT] Auth event: ${event}, hasSession: ${!!session}`,
  );
  // INITIAL_SESSION will now typically be null if persistSession is false
});

// Removed: explicit call to supabaseClient.auth.getSession() that logged any existing session.
// onAuthStateChange will fire with INITIAL_SESSION immediately.

// Create a wrapped client with logging for exports
export const supabase = {
  ...supabaseClient,
  // Add logging to auth methods
  auth: {
    ...supabaseClient.auth, // Spreading methods here can lead to `this` context issues for non-wrapped methods
    signInWithPassword: async (credentials: {
      email: string;
      password: string;
    }) => {
      console.log(`🔌 [SUPABASE] Attempting sign in for: ${credentials.email}`);
      const result = await supabaseClient.auth.signInWithPassword(credentials);
      console.log("🔌 [SUPABASE] Sign in result:", {
        success: !result.error,
        errorMessage: result.error?.message,
        hasUser: !!result.data.user,
        hasSession: !!result.data.session,
      });
      return result;
    },
    signUp: async (credentials: SignUpWithPasswordCredentials) => {
      console.log(`🔌 [SUPABASE] Attempting sign up for: ${credentials.email}`);
      const result = await supabaseClient.auth.signUp(credentials);
      console.log("🔌 [SUPABASE] Sign up result:", {
        success: !result.error,
        errorMessage: result.error?.message,
        hasUser: !!result.data.user,
        hasSession: !!result.data.session,
      });
      return result;
    },
    signOut: async () => {
      console.log("🔌 [SUPABASE] Signing out user");
      const result = await supabaseClient.auth.signOut();
      console.log("🔌 [SUPABASE] Sign out result:", {
        success: !result.error,
        errorMessage: result.error?.message,
      });
      return result;
    },
    getSession: async () => {
      console.log("🔌 [SUPABASE] Getting session");
      const result = await supabaseClient.auth.getSession();
      console.log("🔌 [SUPABASE] Get session result:", {
        success: !result.error,
        hasSession: !!result.data.session,
      });
      return result;
    },
    onAuthStateChange: (
      callback: (event: AuthChangeEvent, session: Session | null) => void,
    ) => {
      console.log(
        "🔌 [SUPABASE WRAPPER] Registering onAuthStateChange callback",
      );
      // Call the original onAuthStateChange method on the original supabaseClient.auth object
      // This ensures 'this' inside onAuthStateChange refers to supabaseClient.auth
      const result = supabaseClient.auth.onAuthStateChange(callback);
      console.log(
        "🔌 [SUPABASE WRAPPER] onAuthStateChange subscription successful:",
        { hasSubscription: !!result.data.subscription },
      );
      return result;
    },
  },
  // Add Storage API with logging
  storage: {
    from: (bucketName: string) => {
      console.log(`🔌 [SUPABASE] Storage operation on bucket: ${bucketName}`);
      return supabaseClient.storage.from(bucketName);
    },
  },
  // Forward other methods directly with type preservation
  from: <T extends keyof Database["public"]["Tables"]>(table: T) => {
    console.log(`🔌 [SUPABASE] Database query on table: ${table}`);
    return supabaseClient.from(table);
  },
  rpc: <T extends keyof Database["public"]["Functions"]>(
    fn: T,
    params?: Database["public"]["Functions"][T]["Args"],
  ) => {
    console.log(`🔌 [SUPABASE] RPC call to function: ${fn}`);
    return supabaseClient.rpc(fn, params);
  },
  // Add Realtime capabilities with logging
  channel: (name: string, opts?: any) => {
    console.log(`🔌 [SUPABASE] Creating Realtime channel: ${name}`, opts);
    return supabaseClient.channel(name, opts);
  },
  realtime: {
    ...supabaseClient.realtime,
    setAuth: async (token?: string | null) => {
      console.log("🔌 [SUPABASE] Setting Realtime auth token");
      const result = await supabaseClient.realtime.setAuth(token);
      console.log("🔌 [SUPABASE] Realtime auth result: completed");
      return result;
    },
  },
  removeChannel: (channel: any) => {
    console.log("🔌 [SUPABASE] Removing Realtime channel");
    return supabaseClient.removeChannel(channel);
  },
};
